# Generated by Django 5.0.6 on 2024-08-29 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_smtp_mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SMTP_Mail',
            new_name='SMTPMail',
        ),
    ]
