# Generated by Django 5.0.6 on 2024-08-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_smtp_mail', '0002_rename_smtp_mail_smtpmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smtpmail',
            old_name='smtp_username',
            new_name='smtp_email',
        ),
        migrations.RemoveField(
            model_name='smtpmail',
            name='smtp_host',
        ),
        migrations.AddField(
            model_name='smtpmail',
            name='smtp_server',
            field=models.CharField(default='smtp.gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpmail',
            name='smtp_port',
            field=models.IntegerField(default=465),
        ),
    ]
