# Generated by Django 5.0.6 on 2024-08-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_smtp_mail', '0003_rename_smtp_username_smtpmail_smtp_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpmail',
            name='smtp_password',
            field=models.CharField(max_length=255),
        ),
    ]
