# Generated by Django 5.0.6 on 2024-08-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_smtp_mail', '0004_alter_smtpmail_smtp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpmail',
            name='smtp_hash',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
