# Generated by Django 5.0.6 on 2024-08-29 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_smtp_mail', '0005_smtpmail_smtp_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpmail',
            name='smtp_hash',
        ),
    ]
