# Generated by Django 5.0.6 on 2024-06-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_cart', '0002_rename_created_at_cart_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='public_id',
        ),
    ]
